version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["node", "--env-file=.env", "server/start.js"]
    ports:
      - "3001:3001"
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - default
      - sharednet
    environment:
      - NODE_ENV=development
      # Add other env vars as needed

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["npm", "run", "dev"]
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      # Add other env vars as needed

networks:
  sharednet:
    external: true