version: "3.8"

services:
  backend:
    container_name: aeron-rm
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - default
      - sharednet
    environment:
      - NODE_ENV=development
      # Add other env vars as needed
    command: sh -c "npm run build && node --env-file=.env server/start.js"

networks:
  sharednet:
    external: true